### ISSUE TITLE
Why the SN74HC245N is needed to read the ROM?

### ISSUE THREAD

**Issue by odelot** [dcooperdalrymple/picoprom#2]
Hi,

nice video and fork you have here ;-) 

I was confused why the SN74HC245N is needed to read the rom? Can you tell me why? (I really do not know. I was trying to read direct and I coudn't, and I cannot understand why since PICO GPIOs are 5v tolerants)

I thought it was just change the data pins from output to input, but it seems this do not work. 

Thanks in advance,

Fábio

**Comment by relic-se** [comment]
Sorry for the delay in responding to your issue. Although many Pico users have had success using 5V logic directly with GPIO without the use of level shifters, it is technically out of spec with the MCU's capabilities and not recommended for long-term deployments. If you are temporarily experimenting with this project, it is likely okay to test EEPROM reading capabilities directly with the GPIO of the RP2040, but don't take that as a recommendation in any way and you do run the risk of damaging your device. Most projects similar to this one (ie: RP2040-based rom carts, vintage computer peripherals, etc) utilize 5V level shifters for the same reasons.

5V TTL logic on the other hand is tolerant to 3.3V input. This is why the control signals are handled directly by the RP2040's GPIO and only the data bus requires a level shifter.
